"""empty message

Revision ID: 6fefa5ba9421
Revises: c2e9c38a7236
Create Date: 2019-06-26 07:28:32.761481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fefa5ba9421'
down_revision = 'c2e9c38a7236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'insider', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'insider', type_='unique')
    # ### end Alembic commands ###
