"""empty message

Revision ID: c2e9c38a7236
Revises: e2a1a5712489
Create Date: 2019-06-26 06:19:50.159162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e9c38a7236'
down_revision = 'e2a1a5712489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('volume', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price', 'volume')
    # ### end Alembic commands ###
